name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Emacs
        run: |
          sudo apt-get install emacs-nox
      - name: Set up Cask
        uses: conao3/setup-cask@master
      - name: Test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          make test
